/Users/haotianyang/test/pytorch-from-centralized-to-federated/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[92mINFO [0m:      
[92mINFO [0m:      Received: evaluate message 8c8be53e-99f7-44bb-9cde-c3a5ba9ed558
Client Evaluation: 
Test Accuracy: 0.088, Test Loss: 230.38200306892395
[92mINFO [0m:      Sent reply
[92mINFO [0m:      
[92mINFO [0m:      Received: train message d481c35e-0489-4766-abba-96c8f3820d0c
Train Epoch: 0 [0/600 (0%)]	Loss: 2.297978
Test Accuracy: 0.0973, Test Loss: 230.27498269081116
[92mINFO [0m:      Sent reply
[92mINFO [0m:      
[92mINFO [0m:      Received: evaluate message dd2138ae-f300-43f4-a402-54e723341dba
Client Evaluation: 
Test Accuracy: 0.0949, Test Loss: 230.25880360603333
[92mINFO [0m:      Sent reply
E0705 13:58:35.611089000 14475440128 tcp_posix.cc:598]                 recvmsg encountered uncommon error: Message too long
[92mINFO [0m:      
[92mINFO [0m:      Received: train message 17516823-726f-4b00-a4fe-5a9d6a966035
Train Epoch: 0 [0/600 (0%)]	Loss: 2.305258
Test Accuracy: 0.1015, Test Loss: 230.1435215473175
[92mINFO [0m:      Sent reply
E0705 13:59:51.459622000 14475440128 tcp_posix.cc:598]                 recvmsg encountered uncommon error: Message too long
[92mINFO [0m:      
[92mINFO [0m:      Received: evaluate message 02f57e05-e2fb-4177-9040-2bb55bd2788e
Client Evaluation: 
Test Accuracy: 0.1014, Test Loss: 230.1357123851776
[92mINFO [0m:      Sent reply
[92mINFO [0m:      
[92mINFO [0m:      Received: train message 8ae2acb9-fd7d-4114-95a8-ce81f0a1184d
Train Epoch: 0 [0/600 (0%)]	Loss: 2.305818
Test Accuracy: 0.1055, Test Loss: 230.01805591583252
[92mINFO [0m:      Sent reply
E0705 14:01:28.214179000 14475440128 tcp_posix.cc:598]                 recvmsg encountered uncommon error: Message too long
[92mINFO [0m:      
[92mINFO [0m:      Received: evaluate message 561332a8-8807-41e2-9634-62aa7a06bf61
Client Evaluation: 
Test Accuracy: 0.1074, Test Loss: 230.011225938797
[92mINFO [0m:      Sent reply
[92mINFO [0m:      
[92mINFO [0m:      Received: train message 5249aa5b-7dd5-41c8-bbd8-0823efea2a73
Train Epoch: 0 [0/600 (0%)]	Loss: 2.303837
Test Accuracy: 0.1103, Test Loss: 229.89668822288513
[92mINFO [0m:      Sent reply
E0705 14:02:51.151975000 14475440128 tcp_posix.cc:598]                 recvmsg encountered uncommon error: Message too long
[92mINFO [0m:      
[92mINFO [0m:      Received: evaluate message b8a0dbcb-26bc-4698-98c7-9f314e51c4cd
Client Evaluation: 
Test Accuracy: 0.1141, Test Loss: 229.8874170780182
[92mINFO [0m:      Sent reply
[92mINFO [0m:      
[92mINFO [0m:      Received: train message 3392ccc6-0473-4391-84b4-b60fb1f37632
Train Epoch: 0 [0/600 (0%)]	Loss: 2.303762
Test Accuracy: 0.1152, Test Loss: 229.7764208316803
[92mINFO [0m:      Sent reply
E0705 14:11:29.366737000 14475440128 tcp_posix.cc:598]                 recvmsg encountered uncommon error: Message too long
[92mINFO [0m:      
[92mINFO [0m:      Received: evaluate message 647a7e54-3220-477f-bbb8-018b0d534efc
Client Evaluation: 
Test Accuracy: 0.1186, Test Loss: 229.76430010795593
[92mINFO [0m:      Sent reply
[92mINFO [0m:      
[92mINFO [0m:      Received: train message 2c2ab56c-9b59-46d5-a5b7-8737618825bd
Train Epoch: 0 [0/600 (0%)]	Loss: 2.302603
Test Accuracy: 0.1189, Test Loss: 229.64350962638855
[92mINFO [0m:      Sent reply
E0705 14:19:21.952615000 14475440128 tcp_posix.cc:598]                 recvmsg encountered uncommon error: Message too long
[92mINFO [0m:      
[92mINFO [0m:      Received: evaluate message 5a5c32c6-d2c9-4d3c-b47c-7c3d3b31e61d
Client Evaluation: 
Test Accuracy: 0.1221, Test Loss: 229.64074635505676
[92mINFO [0m:      Sent reply
[92mINFO [0m:      
[92mINFO [0m:      Received: train message cc89a35a-1cec-48f2-8505-11c67c9cd11d
Train Epoch: 0 [0/600 (0%)]	Loss: 2.292260
Test Accuracy: 0.1221, Test Loss: 229.5209836959839
[92mINFO [0m:      Sent reply
Traceback (most recent call last):
  File "/Users/haotianyang/test/pytorch-from-centralized-to-federated/client.py", line 102, in <module>
    main()
  File "/Users/haotianyang/test/pytorch-from-centralized-to-federated/client.py", line 98, in main
    fl.client.start_client(server_address="127.0.0.1:8080", client=client)
  File "/Users/haotianyang/test/pytorch-from-centralized-to-federated/.venv/lib/python3.9/site-packages/flwr/client/app.py", line 157, in start_client
    _start_client_internal(
  File "/Users/haotianyang/test/pytorch-from-centralized-to-federated/.venv/lib/python3.9/site-packages/flwr/client/app.py", line 333, in _start_client_internal
    message = receive()
  File "/Users/haotianyang/test/pytorch-from-centralized-to-federated/.venv/lib/python3.9/site-packages/flwr/client/grpc_client/connection.py", line 144, in receive
    proto = next(server_message_iterator)
  File "/Users/haotianyang/test/pytorch-from-centralized-to-federated/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 543, in __next__
    return self._next()
  File "/Users/haotianyang/test/pytorch-from-centralized-to-federated/.venv/lib/python3.9/site-packages/grpc/_channel.py", line 969, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "ping timeout"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:8080 {created_time:"2024-07-05T14:28:18.301638-07:00", grpc_status:14, grpc_message:"ping timeout"}"
>
